/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MiracleId = IDL.Nat;
export const MiracleLocation = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
});
export const EucharisticMiracle = IDL.Record({
  'id' : MiracleId,
  'title' : IDL.Text,
  'additionalDetails' : IDL.Opt(IDL.Text),
  'imageUrls' : IDL.Vec(IDL.Text),
  'year' : IDL.Nat,
  'witnessAccounts' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'churchApprovalDate' : IDL.Opt(IDL.Text),
  'currentLocation' : IDL.Opt(IDL.Text),
  'historicalContext' : IDL.Text,
  'location' : MiracleLocation,
  'scientificFindings' : IDL.Opt(IDL.Text),
  'verificationStatus' : IDL.Text,
});
export const SacramentId = IDL.Nat;
export const SacramentCategory = IDL.Variant({
  'Healing' : IDL.Null,
  'Service' : IDL.Null,
  'Initiation' : IDL.Null,
});
export const Sacrament = IDL.Record({
  'id' : SacramentId,
  'spiritualSignificance' : IDL.Text,
  'biblicalRoots' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'symbolImageUrl' : IDL.Text,
  'category' : SacramentCategory,
});
export const SaintId = IDL.Nat;
export const Saint = IDL.Record({
  'id' : SaintId,
  'keyFacts' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'biography' : IDL.Text,
  'feastDay' : IDL.Text,
  'patronage' : IDL.Vec(IDL.Text),
  'portraitImageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMiracle' : IDL.Func(
      [MiracleId],
      [IDL.Opt(EucharisticMiracle)],
      ['query'],
    ),
  'getMiraclesByCountry' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EucharisticMiracle)],
      ['query'],
    ),
  'getSacrament' : IDL.Func([SacramentId], [IDL.Opt(Sacrament)], ['query']),
  'getSaint' : IDL.Func([SaintId], [IDL.Opt(Saint)], ['query']),
  'listMiracles' : IDL.Func([], [IDL.Vec(EucharisticMiracle)], ['query']),
  'listSacraments' : IDL.Func([], [IDL.Vec(Sacrament)], ['query']),
  'listSaints' : IDL.Func([], [IDL.Vec(Saint)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MiracleId = IDL.Nat;
  const MiracleLocation = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
  });
  const EucharisticMiracle = IDL.Record({
    'id' : MiracleId,
    'title' : IDL.Text,
    'additionalDetails' : IDL.Opt(IDL.Text),
    'imageUrls' : IDL.Vec(IDL.Text),
    'year' : IDL.Nat,
    'witnessAccounts' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'churchApprovalDate' : IDL.Opt(IDL.Text),
    'currentLocation' : IDL.Opt(IDL.Text),
    'historicalContext' : IDL.Text,
    'location' : MiracleLocation,
    'scientificFindings' : IDL.Opt(IDL.Text),
    'verificationStatus' : IDL.Text,
  });
  const SacramentId = IDL.Nat;
  const SacramentCategory = IDL.Variant({
    'Healing' : IDL.Null,
    'Service' : IDL.Null,
    'Initiation' : IDL.Null,
  });
  const Sacrament = IDL.Record({
    'id' : SacramentId,
    'spiritualSignificance' : IDL.Text,
    'biblicalRoots' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'symbolImageUrl' : IDL.Text,
    'category' : SacramentCategory,
  });
  const SaintId = IDL.Nat;
  const Saint = IDL.Record({
    'id' : SaintId,
    'keyFacts' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'biography' : IDL.Text,
    'feastDay' : IDL.Text,
    'patronage' : IDL.Vec(IDL.Text),
    'portraitImageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getMiracle' : IDL.Func(
        [MiracleId],
        [IDL.Opt(EucharisticMiracle)],
        ['query'],
      ),
    'getMiraclesByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EucharisticMiracle)],
        ['query'],
      ),
    'getSacrament' : IDL.Func([SacramentId], [IDL.Opt(Sacrament)], ['query']),
    'getSaint' : IDL.Func([SaintId], [IDL.Opt(Saint)], ['query']),
    'listMiracles' : IDL.Func([], [IDL.Vec(EucharisticMiracle)], ['query']),
    'listSacraments' : IDL.Func([], [IDL.Vec(Sacrament)], ['query']),
    'listSaints' : IDL.Func([], [IDL.Vec(Saint)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };