/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EucharisticMiracle {
  'id' : MiracleId,
  'title' : string,
  'additionalDetails' : [] | [string],
  'imageUrls' : Array<string>,
  'year' : bigint,
  'witnessAccounts' : [] | [string],
  'description' : string,
  'churchApprovalDate' : [] | [string],
  'currentLocation' : [] | [string],
  'historicalContext' : string,
  'location' : MiracleLocation,
  'scientificFindings' : [] | [string],
  'verificationStatus' : string,
}
export type MiracleId = bigint;
export interface MiracleLocation { 'country' : string, 'city' : string }
export interface Sacrament {
  'id' : SacramentId,
  'spiritualSignificance' : string,
  'biblicalRoots' : string,
  'name' : string,
  'description' : string,
  'symbolImageUrl' : string,
  'category' : SacramentCategory,
}
export type SacramentCategory = { 'Healing' : null } |
  { 'Service' : null } |
  { 'Initiation' : null };
export type SacramentId = bigint;
export interface Saint {
  'id' : SaintId,
  'keyFacts' : Array<string>,
  'name' : string,
  'biography' : string,
  'feastDay' : string,
  'patronage' : Array<string>,
  'portraitImageUrl' : string,
}
export type SaintId = bigint;
export interface _SERVICE {
  'getMiracle' : ActorMethod<[MiracleId], [] | [EucharisticMiracle]>,
  'getMiraclesByCountry' : ActorMethod<[string], Array<EucharisticMiracle>>,
  'getSacrament' : ActorMethod<[SacramentId], [] | [Sacrament]>,
  'getSaint' : ActorMethod<[SaintId], [] | [Saint]>,
  'listMiracles' : ActorMethod<[], Array<EucharisticMiracle>>,
  'listSacraments' : ActorMethod<[], Array<Sacrament>>,
  'listSaints' : ActorMethod<[], Array<Saint>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];