/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Saint {
    id: SaintId;
    keyFacts: Array<string>;
    name: string;
    biography: string;
    feastDay: string;
    patronage: Array<string>;
    portraitImageUrl: string;
}
export interface MiracleLocation {
    country: string;
    city: string;
}
export type SacramentId = bigint;
export type SaintId = bigint;
export type MiracleId = bigint;
export interface EucharisticMiracle {
    id: MiracleId;
    title: string;
    additionalDetails?: string;
    imageUrls: Array<string>;
    year: bigint;
    witnessAccounts?: string;
    description: string;
    churchApprovalDate?: string;
    currentLocation?: string;
    historicalContext: string;
    location: MiracleLocation;
    scientificFindings?: string;
    verificationStatus: string;
}
export interface Sacrament {
    id: SacramentId;
    spiritualSignificance: string;
    biblicalRoots: string;
    name: string;
    description: string;
    symbolImageUrl: string;
    category: SacramentCategory;
}
export enum SacramentCategory {
    Healing = "Healing",
    Service = "Service",
    Initiation = "Initiation"
}
export interface backendInterface {
    getMiracle(id: MiracleId): Promise<EucharisticMiracle | null>;
    getMiraclesByCountry(country: string): Promise<Array<EucharisticMiracle>>;
    getSacrament(id: SacramentId): Promise<Sacrament | null>;
    getSaint(id: SaintId): Promise<Saint | null>;
    listMiracles(): Promise<Array<EucharisticMiracle>>;
    listSacraments(): Promise<Array<Sacrament>>;
    listSaints(): Promise<Array<Saint>>;
}
import type { EucharisticMiracle as _EucharisticMiracle, MiracleId as _MiracleId, MiracleLocation as _MiracleLocation, Sacrament as _Sacrament, SacramentCategory as _SacramentCategory, SacramentId as _SacramentId, Saint as _Saint } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getMiracle(arg0: MiracleId): Promise<EucharisticMiracle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMiracle(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMiracle(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMiraclesByCountry(arg0: string): Promise<Array<EucharisticMiracle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMiraclesByCountry(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMiraclesByCountry(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSacrament(arg0: SacramentId): Promise<Sacrament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSacrament(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSacrament(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaint(arg0: SaintId): Promise<Saint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaint(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaint(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMiracles(): Promise<Array<EucharisticMiracle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMiracles();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMiracles();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSacraments(): Promise<Array<Sacrament>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSacraments();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSacraments();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSaints(): Promise<Array<Saint>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSaints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSaints();
            return result;
        }
    }
}
function from_candid_EucharisticMiracle_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EucharisticMiracle): EucharisticMiracle {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SacramentCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SacramentCategory): SacramentCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Sacrament_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sacrament): Sacrament {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EucharisticMiracle]): EucharisticMiracle | null {
    return value.length === 0 ? null : from_candid_EucharisticMiracle_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Saint]): Saint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sacrament]): Sacrament | null {
    return value.length === 0 ? null : from_candid_Sacrament_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MiracleId;
    title: string;
    additionalDetails: [] | [string];
    imageUrls: Array<string>;
    year: bigint;
    witnessAccounts: [] | [string];
    description: string;
    churchApprovalDate: [] | [string];
    currentLocation: [] | [string];
    historicalContext: string;
    location: _MiracleLocation;
    scientificFindings: [] | [string];
    verificationStatus: string;
}): {
    id: MiracleId;
    title: string;
    additionalDetails?: string;
    imageUrls: Array<string>;
    year: bigint;
    witnessAccounts?: string;
    description: string;
    churchApprovalDate?: string;
    currentLocation?: string;
    historicalContext: string;
    location: MiracleLocation;
    scientificFindings?: string;
    verificationStatus: string;
} {
    return {
        id: value.id,
        title: value.title,
        additionalDetails: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.additionalDetails)),
        imageUrls: value.imageUrls,
        year: value.year,
        witnessAccounts: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.witnessAccounts)),
        description: value.description,
        churchApprovalDate: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.churchApprovalDate)),
        currentLocation: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.currentLocation)),
        historicalContext: value.historicalContext,
        location: value.location,
        scientificFindings: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.scientificFindings)),
        verificationStatus: value.verificationStatus
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SacramentId;
    spiritualSignificance: string;
    biblicalRoots: string;
    name: string;
    description: string;
    symbolImageUrl: string;
    category: _SacramentCategory;
}): {
    id: SacramentId;
    spiritualSignificance: string;
    biblicalRoots: string;
    name: string;
    description: string;
    symbolImageUrl: string;
    category: SacramentCategory;
} {
    return {
        id: value.id,
        spiritualSignificance: value.spiritualSignificance,
        biblicalRoots: value.biblicalRoots,
        name: value.name,
        description: value.description,
        symbolImageUrl: value.symbolImageUrl,
        category: from_candid_SacramentCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Healing: null;
} | {
    Service: null;
} | {
    Initiation: null;
}): SacramentCategory {
    return "Healing" in value ? SacramentCategory.Healing : "Service" in value ? SacramentCategory.Service : "Initiation" in value ? SacramentCategory.Initiation : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sacrament>): Array<Sacrament> {
    return value.map((x)=>from_candid_Sacrament_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EucharisticMiracle>): Array<EucharisticMiracle> {
    return value.map((x)=>from_candid_EucharisticMiracle_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
